### ISSUE TITLE
Edit Homepage

### ISSUE THREAD

**Issue by inesiwadare** [BlickLabs/vre#1]
The client requested 3 changes in the Homepage design.
- [x] The menu has to stay on top of the page after the first scroll and freeze there. Here's the Design of how it is supposed to look like:

<img width="776" alt="screen shot 2016-08-03 at 6 02 38 pm" src="https://cloud.githubusercontent.com/assets/17226545/17384865/7f42632c-59a4-11e6-83fc-d30ea3e15e92.png">
- [x] Insert a contact form instead of the quote "Desarrollamos..." 
  Example given:

<img width="1167" alt="screen shot 2016-08-03 at 6 03 32 pm" src="https://cloud.githubusercontent.com/assets/17226545/17384878/9ec962a4-59a4-11e6-9bea-dfae4a904d96.png">
- [x] Insert Chat in the bottom right side. (Olark i think) but @amorenoh90 know which one.

New Updates:
- [x] Add a new menu tab "Visita nuestro showroom" after the contact tab in all the menus.

<img width="782" alt="screen shot 2016-08-05 at 6 47 26 pm" src="https://cloud.githubusercontent.com/assets/17226545/17453183/5f12a04a-5b3d-11e6-8e6c-016513d7440f.png">
- [x] Also in the menu we have to add this "| " icon between each tab (it's on the picture above)

**Comment by getmoremx** [comment]
I will send you the embeded Code for Olark @AlanSanchezP

**Comment by getmoremx** [comment]
@AlanSanchezP @inesiwadare The client requested to change the tag name of "Visita nuestro showroom" to "Visítanos".
