### ISSUE TITLE
Bad quality of render pictures 

### ISSUE THREAD

**Issue by getmoremx** [BlickLabs/vre#10]
Cover pictures in both "Desarrollos" views are missing resolution quality.

**Comment by inesiwadare** [comment]
@AlanSanchezP What kind of resolution do you need? like the size of the place where the carousel goes. So i can export the images in a different format.

**Comment by getmoremx** [comment]
@inesiwadare also take a look at the cover photo of each Desarrollo, they are in low quality as well.

**Comment by AlanSanchezP** [comment]
1761x614px would be a good resolution for both cover pictures

**Comment by inesiwadare** [comment]
The new renders are uploaded now. 
Folder: Renders_v2
