### ISSUE TITLE
Picture in mobile version

### ISSUE THREAD

**Issue by getmoremx** [BlickLabs/vre#42]
The client is requesting to fix the issue. The logo doesn't look right when you go to the site on a mobile phone.

**Comment by AlanSanchezP** [comment]
can you attach a screenshot of the issue?

**Comment by getmoremx** [comment]
The opacity is missing. 
![img_6286](https://cloud.githubusercontent.com/assets/8682071/19137585/9d8b0164-8b3a-11e6-8dad-b11534f4904e.PNG)
