### ISSUE TITLE
Insert the following code

### ISSUE THREAD

**Issue by getmoremx** [BlickLabs/vre#48]
Start by adding the JavaScript tracking code below to your site. Copy and paste it into your tag manager or the <head> tag on every page where you wish to track visitors and collect feedback.

<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:337000,hjsv:5};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by MauricioDinki** [comment]
Done
