### ISSUE TITLE
Information for detailed view in new desarrollo

### ISSUE THREAD

**Issue by getmoremx** [BlickLabs/vre#55]
Here is the information for the new building called Tlacotalpan 146. 

Characteristics: 
Sala
Cuarto de servicio
Comedor
Estudio*
Vestidor
Dos a tres recámaras
Dos a tres baños completos
Closet
Cocina equipada
Uno a tres cajones de estacionamiento 
Balcón o terraza *
*Aplica solamente en algunos departamentos 

Google maps: 
https://www.google.com.mx/maps/place/Tlacotalpan+146,+Roma+Sur,+06760+Ciudad+de+M%C3%A9xico,+CDMX/@19.4016774,-99.1675674,17z/data=!4m5!3m4!1s0x85d1ff137bfb8985:0xb6ee3889ae979b1d!8m2!3d19.4019355!4d-99.1653573

Lugares de interés:
Hospital Angeles México: 4 min (900 m)
Angel de la Independencia: 17 min (3 km)
Aeropuerto CDMX: 27 min (12 km)
Antara Fashion Hall: 24 min (8 km)
Centro Comercial Santa Fe: 36 min (14 km)

TRANSPORTE PÚBLICO: Metrobus: Nuevo León (8min, 600m) | Metro: Chilpancingo (10min, 750m) | Ecobici: Calle Bajío (2min, 160m) | Walkscore: 98 (El mismo texto que en los demás)

**Comment by AlanSanchezP** [comment]
@inesiwadare We need the following icons: Estudio, Balcon/Terraza and Hospital Angeles México.

**Comment by inesiwadare** [comment]
Listo :) @AlanSanchezP 
![icoos nuevos vre-02](https://cloud.githubusercontent.com/assets/17226545/20780018/e9fe7628-b73d-11e6-8932-d669fea1cefd.png)
![icoos nuevos vre-03](https://cloud.githubusercontent.com/assets/17226545/20780019/ea0e5048-b73d-11e6-9163-2629e0d6694e.png)
![icoos nuevos vre-04](https://cloud.githubusercontent.com/assets/17226545/20780020/ea1532e6-b73d-11e6-9e4a-037164caa53e.png)
