### ISSUE TITLE
VRE_v2 

### ISSUE THREAD

**Issue by getmoremx** [BlickLabs/vre#70]
This issue is for the redesign of the website. There are just three parts that we need to work on:
1. Homepage - grid of Desarrollos
2. Homepage - 360 video
3. Desarrollos view
4. Add one more Desarrollo

'1. The details are on Zeplin but the order should be the following: Nebraska, Tlacotalpan, Indiana and Dakota. 
'2. We need to add the current 360 videos plus a new one. The new one (Nebraska 159) url is the following: http://www.dwmx.com/VRE/Nebraska/. Remember to place an image above the 360 to solve the UX for the user when he scrolls down. 
'3. Desarrollos view: this view is totally different but keep the order as in the homepage. The map above the footer should show all the Desarrollos with their respective pin, just like this map: http://puntodestino.com.mx/#desarrollos. Use mapbox because the next version will be like airbnb and it is a lot more easier to play with mapbox than google maps, also it is free. 
'4. The information for the new Desarrollo is the following: 
- Name: Nebraska 159
- Logo:  @inesiwadare can you help us with this or we need to ask it to the client?
- Main description: Vive en el corazón de la Colonia Nápoles. Departamentos desde 74 a 103 m2.
- Main image: recamara (Ines will send it) 
- Presentation for downloading: it is attached here. 
[VRE - Condos Nápoles - Nebraska.pdf](https://github.com/BlickLabs/vre/files/736705/VRE.-.Condos.Napoles.-.Nebraska.pdf)
- 360: it is above. 
- Characteristics of the apartments: same as Indiana and Dakota (just the same)
- Carrousel: use the same renders as Tlacotalpan plus the main image of this view and the renders that are attached in this issue. 
- Apartments: Ines will send the maps
- Location of the Desarrollo: https://www.google.com.mx/maps/place/Nebraska+159,+N%C3%A1poles,+03810+Ciudad+de+M%C3%A9xico,+CDMX/@19.394935,-99.1788913,17z/data=!3m1!4b1!4m5!3m4!1s0x85d1ff703088f9d1:0x867a4e9007e60df9!8m2!3d19.394935!4d-99.1767026
- Distances: use the icons/logos from other Desarrollos, we already have all of them. 
Hospital Star Medica: 5min (450m)
Angel 19min (5 km)
Aeropuerto 26min (12.2 km)
Antara 15min (7.3km)
Santa Fe 29min (23.3km) 
- Transporte publico: same as Dakota

**Comment by inesiwadare** [comment]
![fachada](https://cloud.githubusercontent.com/assets/17226545/22397532/e878a1ba-e538-11e6-9234-9a6ec6f49834.jpg)
![planta](https://cloud.githubusercontent.com/assets/17226545/22397533/e89a2150-e538-11e6-8840-f9b184623282.jpg)
![plantacenitaln2l](https://cloud.githubusercontent.com/assets/17226545/22397535/e8ac7f76-e538-11e6-87dc-9b9bac1ced35.jpg)
![recamara](https://cloud.githubusercontent.com/assets/17226545/22397534/e8ab5254-e538-11e6-9ea3-fe3d997c65e0.jpg)
